www/oncall/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    # url(r'^reservation/add/((?P<pk>[0-9a-zA-Z]*)/)?$', views.ReservationCreateView.as_view(), name='reservation-create'),
    # url(r'^reservation/view/(?P<pk>[0-9]*)/$', views.ReservationDetailView.as_view(), name='reservation-detail'),
    # url(r'^(?P<status>[0-9a-zA-Z]*)/', views.ReservationListView.as_view(), name='reservation-draft-list'),
    url(r'^$', views.HomeTemplateView.as_view(), name='reservation-list'),
    url(r'^profile/$', views.UserDetailView.as_view(), name='profile-detail'),
]

www/www/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^oncall/', include('oncall.urls', namespace='oncall')),
    url(r'^admin/', admin.site.urls),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

www/oncall/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.core.validators import validate_comma_separated_integer_list
from django.db import models
from django.db.models import Q


class Duty(models.Model):
    HOURS_IN_THE_DAY = [
        [x % 12 + 12 * i, '%s%s' % (x, y)]
        for i, y in enumerate(['am', 'pm'])
        for x in [12] + range(1, 12)
    ] + [[24, '12am (next day)']]

    order_attribute = None

    days_of_week = models.CharField(max_length=16, validators=[validate_comma_separated_integer_list])
    start_time = models.IntegerField(help_text='Hour in the Day', choices=HOURS_IN_THE_DAY)
    stop_time = models.IntegerField(help_text='Hour in the Day', choices=HOURS_IN_THE_DAY)

    def validate_unique(self, *args, **kwargs):
        initial_qs = kwargs.pop('qs') or self.__class__._default_manager.all()
        super(Duty, self).validate_unique(*args, **kwargs)

        if self.start_time == self.stop_time:
            raise ValidationError({
                NON_FIELD_ERRORS: ['Start time and Stop time cannot be the same.', ],
            })

        q_objects = Q()
        for day in self.days_of_week.split(','):
            q_objects.add(Q(days_of_week__contains=day), Q.OR)

        qs = initial_qs.filter(q_objects)
        if not self._state.adding and self.pk is not None:
            qs = qs.exclude(pk=self.pk)

        for obj in qs:
            next_day_for_x, next_day_for_y = 0, 0
            if self.start_time > self.stop_time:
                next_day_for_x = 12
            if obj.start_time > obj.stop_time:
                next_day_for_y = 12
            x = range(self.start_time, self.stop_time + next_day_for_x)
            y = range(obj.start_time, obj.stop_time + next_day_for_y)
            if set(x).intersection(y):
                raise ValidationError({
                    NON_FIELD_ERRORS: ['You have an overlapping date range.', ],
                })

        # #####################################
        # # Search for next day conflicts now #
        # #####################################
        # q_objects = Q()
        # for day in self.days_of_week.split(','):
        #     q_objects.add(Q(days_of_week__contains=day), Q.OR)
        #
        # qs = initial_qs.filter(q_objects)
        # if not self._state.adding and self.pk is not None:
        #     qs = qs.exclude(pk=self.pk)
        #
        # for obj in qs:
        #     next_day_for_x, next_day_for_y = 0, 0
        #     if self.start_time > self.stop_time:
        #         next_day_for_x = 12
        #     if obj.start_time > obj.stop_time:
        #         next_day_for_y = 12
        #     x = range(self.start_time, self.stop_time + next_day_for_x)
        #     y = range(obj.start_time, obj.stop_time + next_day_for_y)
        #     if set(x).intersection(y):
        #         raise ValidationError({
        #             NON_FIELD_ERRORS: ['You have an overlapping date range.', ],
        #         })

    def get_days_of_week_display(self):
        DAYS_OF_WEEK = ['M', 'T', 'W', 'Th', 'F', 'S', 'Su']
        return ', '.join([DAYS_OF_WEEK[int(x)] for x in self.days_of_week.split(',')])

    class Meta:
        abstract = True


class UserProfile(models.Model):
    """
    Default User Profile that ties extra attributes to user
    """

    user = models.OneToOneField('auth.User', related_name='profile')
    notify = models.BooleanField(help_text='Notify when on-call', default=False)

    def __str__(self):
        return self.user.__str__()

    def __unicode__(self):
        return self.__str__()


class ContactMethod(models.Model):
    CONTACT_METHOD_OPTIONS = (
        ('email', 'Email'),
        ('phone', 'Phone'),
        ('text', 'Text Message'),
        ('webhook', 'Webhook'),
    )
    user_profile = models.ForeignKey('oncall.UserProfile')
    method = models.CharField('Email/Phone/Text', choices=CONTACT_METHOD_OPTIONS, max_length=16)
    details = models.CharField(max_length=64)

    def __str__(self):
        return '{}: {}'.format(self.get_method_display(), self.details)

    def __unicode__(self):
        return self.__str__()


class ContactPreference(Duty):
    user = models.ForeignKey('auth.User')
    contact_method = models.ForeignKey('oncall.ContactMethod')

    def validate_unique(self, *args, **kwargs):
        qs = self.__class__._default_manager.filter(user=self.user)
        super(ContactPreference, self).validate_unique(qs=qs, *args, **kwargs)

    def __str__(self):
        return self.user.__str__()

    def __unicode__(self):
        return self.__str__()

    class Meta:
        verbose_name = 'Contact Schedule'
        verbose_name_plural = 'Contact Schedules'


class UsersInRotation(models.Model):
    user = models.ForeignKey('auth.User')
    rotation = models.ForeignKey('oncall.Rotation')
    order = models.IntegerField('Order in the rotation')


class Rotation(Duty):
    """
    The on-call rotations available
    """
    group = models.ForeignKey('auth.Group')
    length = models.IntegerField('Users to be contacted before escalation. Set to zero if primary is always set.')
    users = models.ManyToManyField('auth.User', through='oncall.UsersInRotation')

    def validate_unique(self, *args, **kwargs):
        qs = self.__class__._default_manager.filter(group=self.group)
        super(Duty, self).validate_unique(qs=qs, *args, **kwargs)

    def __str__(self):
        return '{}: {} | {}-{}'.format(
            self.group.__str__(), self.get_days_of_week_display().__str__(),
            self.get_start_time_display(), self.get_stop_time_display(),
        )

    def __unicode__(self):
        return self.__str__()


class RotationsInBundle(models.Model):
    SUPPORT_LEVELS = (
        ('1', 'Tier 2'),
        ('2', 'Tier 3'),
        ('3', 'Management'),
    )
    bundle = models.ForeignKey('oncall.Bundle')
    rotation = models.ForeignKey('oncall.Rotation')
    order = models.IntegerField('Order in the rotation', choices=SUPPORT_LEVELS)


class Bundle(models.Model):
    """ A bundle of Configuration Items that need an on-call rotation"""
    name = models.CharField(max_length=64)
    external_id = models.CharField(max_length=32, blank=True)
    rotations = models.ManyToManyField('oncall.Rotation', through='oncall.RotationsInBundle')

    class Meta:
        verbose_name = 'Support Bundle'
        verbose_name_plural = 'Support Bundles'

www/oncall/forms.py
from django import forms

from . import models
from . import widgets


class ContactPreferenceAdminForm(forms.ModelForm):

    class Meta:
        model = models.ContactPreference
        widgets = {
            'days_of_week': widgets.DaysOfWeekInput(),
        }
        fields = '__all__'


class RotationAdminForm(forms.ModelForm):

    class Meta:
        model = models.Rotation
        widgets = {
            'days_of_week': widgets.DaysOfWeekInput(),
        }
        fields = '__all__'

www/oncall/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from . import models


class HomeTemplateView(LoginRequiredMixin, generic.TemplateView):
    template_name = '200.html'


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.UserProfile

    def get_object(self, queryset=None):
        return self.request.user.profile

www/oncall/templates/200.html
{% extends 'vendors/bootstrap/dashboard.html' %}

{% block navigation_ul %}
    <li><a href="#">Dashboard</a></li>
    <li><a href="#">Settings</a></li>
    <li><a href="{% url 'oncall:profile-detail' %}">Profile</a></li>
    <li><a href="#">Help</a></li>
{% endblock navigation_ul %}

www/oncall/templates/oncall/userprofile_detail.html
{% extends '200.html' %}

www/oncall/templates/vendors/bootstrap/dashboard.html
<!DOCTYPE html> {% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'vendors/bootstrap/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% block navigation_ul %}
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
            {% endblock navigation_ul %}
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'js/vendor/holder.min.js' %}"></script>
  </body>
</html>

www/oncall/templates/vendors/bootstrap/jumbotron.html
<!DOCTYPE html> {% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Jumbotron Template for Bootstrap</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Custom styles for this template -->
        <link href="{% static 'vendors/bootstrap/jumbotron.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>